### ISSUE TITLE
Bug report & app suggestions

### ISSUE THREAD

**Issue by aklohr** [movestore/Corridors#3]
Hi Anne-
I was testing this App for the upcoming Y2Y workshop and had a couple suggestions / wanted to report a bug.

Bug:
- I was unable to zoom in on the map (double-clicking did not do anything)

Suggestions:
- would it be possible to incorporate a background map(s) to provide context for the tracks?
- I found the legend to be a little confusing...it appears the cluster segments and the windows (circles) are all included in the legend list. Do we need to list both? Would including only the identified cluster segments in the legend suffice?
- Probably not as easy to incorporate, but in addition to a tab for each individual animal, can we add a tab to show all the animals on one map? Then users could easily see which corridors receive the most use by all or most animals in the analysis.

Thanks!
Ashley

**Comment by annescharf** [comment]
Hi @aklohr , sorry also here for the very late answer. 
- zooming in works for me. you have to select the area where you want to zoom in (hold left click of mouse down), once you are done, without moving the mouse, release, and double click. 
- I do not remember why I could not add the background map. I'll check again, maybe whatever was not working is solved now.
- legend: the color of the circle and the dots that fall with in it should be the same (i realized that that is not always the case, I'll try to fix this bug). See in the image below how it changes when changing the radius value:
![example_corridors](https://user-images.githubusercontent.com/50947731/233731819-f3b099e0-c067-4921-9176-3faf8fd5bd91.png)
- currently for each individual different settings can be used, so putting the all on one plot could be tricky. Maybe what I can try to do, it to give the option to use the same settings for all individuals and display them all on one map.

ps: you can include images here by dragging them into this box.

**Comment by annescharf** [comment]
I think all of these suggestions and issues have been solved with the new Apps "Corridor Use Behavior - Per Track" and "Corridor Use Behavior - All Tracks"
