### ISSUE TITLE
The data set includes double timestamps per ID

### ISSUE THREAD

**Issue by cleemansen** [movestore/Corridors#6]
## REPRODUCTION

1. Build WF with Apps 
    1. Movebank Location (move2), 
    2. this App (in App-Version see [0])
3. Configure Movebank Location App with values shown in [1]
4. Start the WF
5. Open the UI of this App
6. Select _All tracks_
7. The app crashes with
```
Listening on http://0.0.0.0:3838
Warning: Error in h: error in evaluating the argument 'x' in selecting a method for function 'moveStack': The data set includes double timestamps per ID (first one:Peaches.....DER.AN917..eobs.3916...deploy_id.23461911. unknown 2014-08-06 09:19:35)
  44: <Anonymous>
  43: stop
  42: value[[3L]] [/home/moveapps/co-pilot-r/app.R#68]
  41: tryCatchOne
  40: tryCatchList
  39: tryCatch
  38: server [/home/moveapps/co-pilot-r/app.R#38]
   1: shiny::runApp [/tmp/RtmpuHRXP9/R.INSTALL668fb3590b6/shiny/R/runapp.R#388]
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'moveStack': The data set includes double timestamps per ID (first one:Peaches.....DER.AN917..eobs.3916...deploy_id.23461911. unknown 2014-08-06 09:19:35)
```

---

- [0]: `Scharf, A. K. 2023-12-19. Corridor Use Behavior. version v.3.0 (2). MoveApps. https://github.com/movestore/Corridors.git`
- [1] Movebank Location App Configuration
<img width="874" alt="image" src="https://github.com/movestore/Corridors/assets/868171/d43d540d-3d17-4dd4-92b4-a0ed3951e54e">

**Comment by annescharf** [comment]
@cleemansen I cannot reproduce the error. I ran it locally and on www, and in both cases it worked fine... strange

**Comment by cleemansen** [comment]
Today I also cannot reproduce the reported behavior. That is indeed strange.

**Comment by annescharf** [comment]
thanks for checking!
